#!/usr/bin/python3
import sys

def do_it(n):
  for i in range(2, n + 1):
    if n % i == 0:
      break
  if i == n:
    return str(n) + "=" + str(n) + "*" + str(1)
  return str(n) + "=" + str(n // i) + "*" + str(i)

file = open(sys.argv[1])
L = file.readlines()
for x in L[:-1]:
  s = do_it(int(x))
  print(s)